version: 2
jobs:
  build_and_publish:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build + publish docker image.
          command: |
            docker build --pull -t verath/timatch .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push verath/timatch

workflows:
  version: 2
  build_workflow:
    jobs:
      - build_and_publish:
          filters:
            branches:
              only: master
